SELECT
  YEAR(SALES_DATE) AS YEAR,
  MONTH(SALES_DATE) AS MONTH,
  U.GENDER,
  COUNT(DISTINCT O.USER_ID) AS USERS
FROM USER_INFO U JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), U.GENDER
ORDER BY year, month, U.GENDER ASC;