SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE (AGE BETWEEN 20 AND 29) AND (JOINED LIKE '2021%');

-- # SELECT COUNT(*) AS USERS -> 부속질의 활용
-- # FROM (
-- #     SELECT *
-- #     FROM USER_INFO
-- #     WHERE JOINED LIKE '2021%'
-- # ) AS joined_users
-- # WHERE AGE BETWEEN 20 AND 29;